MPI plugin can now be compiled dinamically

diff --git a/src/arch/mpi/Makefile.am b/src/arch/mpi/Makefile.am
--- a/src/arch/mpi/Makefile.am
+++ b/src/arch/mpi/Makefile.am
@@ -17,8 +17,6 @@
 #      along with NANOS++.  If not, see <http://www.gnu.org/licenses/>.             #
 #####################################################################################
 
-SUBDIRS = performance debug instrumentation instrumentation-debug
-
 include $(top_srcdir)/src/common.am
 
 pkginclude_HEADERS=\
@@ -73,90 +71,32 @@ noinst_LTLIBRARIES =
 debug_LTLIBRARIES =
 instrumentation_LTLIBRARIES =
 instrumentation_debug_LTLIBRARIES =
-performance_LTLIBRARIES =
+performance_LTLIBRARIES = 
 
 
-if PERFORMANCE_VERSION
-noinst_LTLIBRARIES += libmpi.la
-performance_LTLIBRARIES += libnanox-mpi-api.la
-performance_LTLIBRARIES += libnanox-pe-mpi.la
+install-exec-local:
 
-nanos_perfo_cxxflags=$(common_includes) $(common_perfo_cxxflags) $(mpi_ult_flags)
-
-libmpi_la_CXXFLAGS=$(nanos_perfo_cxxflags) $(mpi_api_flags)
-libmpi_la_SOURCES=$(mpi_sources) $(mpi_api_sources)
-
-libnanox_mpi_api_la_CXXFLAGS=$(nanos_perfo_cxxflags) $(mpi_api_flags)
-libnanox_mpi_api_la_LDFLAGS=$(version_flags)
-libnanox_mpi_api_la_SOURCES=$(mpi_api_sources)
-
-libnanox_pe_mpi_la_CXXFLAGS=$(nanos_perfo_cxxflags) $(mpi_api_flags)
-libnanox_pe_mpi_la_LDFLAGS=$(ld_plugin_flags)
-libnanox_pe_mpi_la_LIBADD=$(common_libadd)
-libnanox_pe_mpi_la_SOURCES=$(pe_mpi_sources)
-endif
-
-
+	command -v rsync  >/dev/null && rsync -az --include=*/ --include=*.h --include=*.hpp --exclude=* $(top_srcdir)/src/ $(NANOX_MPI_PREFIX)/src || (echo "rsync not found, using cp" ; cp -R $(top_srcdir)/src/ $(NANOX_MPI_PREFIX)/)
+	cp -R $(top_srcdir)/src/arch/mpi $(NANOX_MPI_PREFIX)/src/arch/
+	chmod 755 $(top_srcdir)/src 
 
 if DEBUG_VERSION
-noinst_LTLIBRARIES += libmpi.la
-debug_LTLIBRARIES += libnanox-mpi-api.la
-debug_LTLIBRARIES += libnanox-pe-mpi.la
-
-
-nanos_debug_cxxflags=$(common_includes) $(common_debug_cxxflags) $(mpi_ult_flags)
-
-libmpi_la_CXXFLAGS=$(nanos_debug_cxxflags)  $(mpi_api_flags)
-libmpi_la_SOURCES=$(mpi_sources) $(mpi_api_sources)
-
-libnanox_mpi_api_la_CXXFLAGS=$(nanos_debug_cxxflags) $(mpi_api_flags)
-libnanox_mpi_api_la_LDFLAGS=$(version_flags)
-libnanox_mpi_api_la_SOURCES=$(mpi_api_sources)
-
-libnanox_pe_mpi_la_CXXFLAGS=$(nanos_debug_cxxflags) $(mpi_api_flags)
-libnanox_pe_mpi_la_LDFLAGS=$(ld_plugin_flags)
-libnanox_pe_mpi_la_LIBADD=$(common_libadd)
-libnanox_pe_mpi_la_SOURCES=$(pe_mpi_sources)
+nanos_debug_cxxflags=$(common_includes) $(common_debug_cxxflags) ${mpi_api_flags}
+	echo ${nanos_debug_cxxflags} | sed "s@${top_srcdir}@${NANOX_MPI_PREFIX}@g" > $(NANOX_MPI_PREFIX)/src/arch/mpi/debug_flags
 endif
 
 if INSTRUMENTATION_VERSION
-noinst_LTLIBRARIES += libmpi.la
-instrumentation_LTLIBRARIES += libnanox-mpi-api.la
-instrumentation_LTLIBRARIES += libnanox-pe-mpi.la
-
-
-nanos_instr_cxxflags=$(common_includes) $(common_instr_cxxflags) $(mpi_ult_flags)
-
-libmpi_la_CXXFLAGS=$(nanos_instr_cxxflags)  $(mpi_api_flags)
-libmpi_la_SOURCES=$(mpi_sources) $(mpi_api_sources)
-
-libnanox_mpi_api_la_CXXFLAGS=$(nanos_instr_cxxflags) $(mpi_api_flags)
-libnanox_mpi_api_la_LDFLAGS=$(version_flags)
-libnanox_mpi_api_la_SOURCES=$(mpi_api_sources)
-
-libnanox_pe_mpi_la_CXXFLAGS=$(nanos_instr_cxxflags) $(mpi_api_flags)
-libnanox_pe_mpi_la_LDFLAGS=$(ld_plugin_flags)
-libnanox_pe_mpi_la_LIBADD=$(common_libadd)
-libnanox_pe_mpi_la_SOURCES=$(pe_mpi_sources)
+nanos_instr_cxxflags=$(common_includes) $(common_instr_cxxflags) ${mpi_api_flags}
+	echo ${nanos_instr_cxxflags} | sed "s@${top_srcdir}@${NANOX_MPI_PREFIX}@g" > $(NANOX_MPI_PREFIX)/src/arch/mpi/instrumentation_flags
 endif
 
 if INSTRUMENTATION_DEBUG_VERSION
-noinst_LTLIBRARIES += libmpi.la
-instrumentation_debug_LTLIBRARIES += libnanox-mpi-api.la
-instrumentation_debug_LTLIBRARIES += libnanox-pe-mpi.la
+nanos_instrdebug_cxxflags=$(common_includes) $(common_instrdebug_cxxflags) ${mpi_api_flags}
+	echo ${nanos_instrdebug_cxxflags} | sed "s@${top_srcdir}@${NANOX_MPI_PREFIX}@g" > $(NANOX_MPI_PREFIX)/src/arch/mpi/instrumentation_debug_flags
+endif
 
 
-nanos_instrdebug_cxxflags=$(common_includes) $(common_instrdebug_cxxflags) $(mpi_ult_flags)
-
-libmpi_la_CXXFLAGS=$(nanos_instrdebug_cxxflags)  $(mpi_api_flags)
-libmpi_la_SOURCES=$(mpi_sources) $(mpi_api_sources)
-
-libnanox_mpi_api_la_CXXFLAGS=$(nanos_instrdebug_cxxflags) $(mpi_api_flags)
-libnanox_mpi_api_la_LDFLAGS=$(version_flags)
-libnanox_mpi_api_la_SOURCES=$(mpi_api_sources)
-
-libnanox_pe_mpi_la_CXXFLAGS=$(nanos_instrdebug_cxxflags) $(mpi_api_flags)
-libnanox_pe_mpi_la_LDFLAGS=$(ld_plugin_flags)
-libnanox_pe_mpi_la_LIBADD=$(common_libadd)
-libnanox_pe_mpi_la_SOURCES=$(pe_mpi_sources)
+if PERFORMANCE_VERSION
+nanos_perfo_cxxflags=$(common_includes) $(common_perfo_cxxflags) ${mpi_api_flags}
+	echo ${nanos_perfo_cxxflags} | sed "s@${top_srcdir}@${NANOX_MPI_PREFIX}@g" > $(NANOX_MPI_PREFIX)/src/arch/mpi/performance_flags 
 endif
